### ISSUE TITLE
error when installing dependencies

### ISSUE THREAD

**Issue by css310310** [shravan-d/SculptMate#1]
when installing the dependencies i get the error

Command '['C:\\Program Files\\Blender Foundation\\Blender 4.1\\4.1\\python\\bin\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/facebookresearch/segment-anything.git']' returned non-zero exit status 1.

**Comment by shravan-d** [comment]
This error occurs for those systems that do not have git installed. One solution is to install git - you can find clear instructions to download and install via [their official page](https://git-scm.com/downloads). 

Another thing I could try to do is get rid of the dependency on Git, which could be a later feature.

**Comment by shravan-d** [comment]
Git is no longer a dependency. Marking this issue as closed.
